spring.application.name=campus_courier

#points towards the local database
spring.datasource.url = jdbc:postgresql://localhost:5432/campus_courier

spring.datasource.username = postgres
spring.datasource.password = Aakash@#23

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql = true